---
title: "CompleteHeatmap_Part2"
author: "Brandon"
date: "12/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

#BiocManager::install("ComplexHeatmap")

library(ComplexHeatmap)
```

# What are annotation and Why we use them? 

```{r}
set.seed(123)
mat = matrix(rnorm(100), 10)
rownames(mat) = paste0("R", 1:10)
colnames(mat) = paste0("C", 1:10)
column_ha = HeatmapAnnotation(foo1 = runif(10), bar1 = anno_barplot(runif(10)))
row_ha = rowAnnotation(foo2 = runif(10), bar2 = anno_barplot(runif(10)))

Heatmap(mat, name = "mat", top_annotation = column_ha, right_annotation = row_ha)
Heatmap(mat, name = "mat", bottom_annotation = column_ha, left_annotation = row_ha)
```

# Understanding Annotation Objects
```{r}
column_ha = HeatmapAnnotation(foo1 = runif(10), bar1 = anno_barplot(runif(10)))

foo1 = runif(10)
bar1 = anno_barplot(runif(10))

column_ha 
```

```{r}
row_ha = rowAnnotation(foo2 = runif(10), bar2 = anno_barplot(runif(10)))
row_ha                    
```

# Simple colored Annotation 

```{r}
ha = columnAnnotation(foo = 1:10)

Heatmap(mat) %v% ha
```


```{r}
ha <- columnAnnotation(bar = sample(letters[1:3], 10, replace = TRUE))
Heatmap(mat) %v% ha
```

```{r}
library(circlize)
col_fun = colorRamp2(c(0, 5, 10), c("blue", "white", "red"))
ha = columnAnnotation(
    foo = 1:10, 
    bar = sample(letters[1:3], 10, replace = TRUE),
    col = list(foo = col_fun,
               bar = c("a" = "red", "b" = "green", "c" = "blue")
    )
)

Heatmap(mat) %v% ha
```
```{r}
library(circlize)
col_fun = colorRamp2(c(0, 5, 10), c("blue", "white", "red"))
ha = columnAnnotation(
    foo = 1:10, 
    bar = sample(letters[1:3], 10, replace = TRUE),
    col = list(foo = col_fun,
               bar = c("a" = "red", "b" = "green", "c" = "blue")
    ),
    border = TRUE
)

Heatmap(mat) %v% ha
```

```{r}
library(circlize)
col_fun = colorRamp2(c(0, 5, 10), c("blue", "white", "red"))
ha = rowAnnotation(
    foo = 1:10, 
    bar = sample(letters[1:3], 10, replace = TRUE),
    col = list(foo = col_fun,
               bar = c("a" = "red", "b" = "green", "c" = "blue")
    ),
    border = TRUE
)

Heatmap(mat) + ha

```
# Points Annotation 
```{r}
ha = HeatmapAnnotation(foo = anno_points(runif(10)), which='column')
Heatmap(mat) %v% ha

ha = HeatmapAnnotation(foo = anno_points(runif(10)), which='row')
Heatmap(mat) + ha
```
# Line Annotation 
```{r}
ha = HeatmapAnnotation(foo = anno_lines(runif(10)), which='column')
Heatmap(mat) %v% ha

ha = HeatmapAnnotation(foo = anno_lines(runif(10)), which='row')
Heatmap(mat) + ha

```

# Bar Annotation  
```{r}
ha = HeatmapAnnotation(foo =  anno_barplot(runif(10)), which='column')
Heatmap(mat) %v% ha

ha = HeatmapAnnotation(foo =  anno_barplot(runif(10)), which='row')
Heatmap(mat) + ha

```


# Histogram Annotation  
```{r}
m = matrix(rnorm(1000), nc = 100)

ha = HeatmapAnnotation(foo = anno_histogram(m), which='row')
Heatmap(mat) + ha

```


# Density Annotation  
```{r}
m = matrix(rnorm(1000), nc = 100)

ha = HeatmapAnnotation(foo = anno_density(m), which='row')
Heatmap(mat) + ha

ha = HeatmapAnnotation(foo = anno_density(m,type = "violin", gp = gpar(fill = 1:10)), which='row')
Heatmap(mat) + ha

```

# Text Annotation
```{r}
ha = rowAnnotation(foo = anno_text(month.name[1:10], gp = gpar(fontsize = 1:12+4)))
Heatmap(mat) + ha
```

# Summary Annotation
```{r}

ha = HeatmapAnnotation(summary = anno_summary(height = unit(4, "cm")))
v = sample(letters[1:2], 50, replace = TRUE)
split = sample(letters[1:2], 50, replace = TRUE)

Heatmap(v)

Heatmap(v, name = "mat", col = c("a" = "red", "b" = "blue"))

Heatmap(v, name = "mat", col = c("a" = "red", "b" = "blue"), top_annotation = ha)

Heatmap(v, name = "mat", col = c("a" = "red", "b" = "blue"), top_annotation = ha, width = unit(2, "cm"), row_split = split)

```


```{r}
ha = HeatmapAnnotation(summary = anno_summary(gp = gpar(fill = 2:3), height = unit(4, "cm")))
v = rnorm(50)
split = sample(letters[1:2], 50, replace = TRUE)

Heatmap(v, name = "mat")
Heatmap(v, name = "mat",top_annotation = ha)      
Heatmap(v, name = "mat",top_annotation = ha, width = unit(2, "cm"))  
Heatmap(v, name = "mat",top_annotation = ha, width = unit(2, "cm"), row_split = split)
```
```{r}
ha = HeatmapAnnotation(summary = anno_summary(gp = gpar(fill = 2:3), height = unit(4, "cm")))

v = rnorm(50)

Heatmap(v, name = "mat")
Heatmap(v, name = "mat", bottom_annotation = ha)      
Heatmap(v, name = "mat" ,bottom_annotation = ha, width = unit(2, "cm"))  
```



```{r}
m = matrix(rnorm(50*10), nrow = 50)
ht_list = Heatmap(m, name = "main_matrix")

ha = HeatmapAnnotation(summary = anno_summary(height = unit(3, "cm")))
v = sample(letters[1:2], 50, replace = TRUE)
ht_list = ht_list + Heatmap(v, name = "mat1", top_annotation = ha, width = unit(1, "cm"))

ha = HeatmapAnnotation(summary = anno_summary(gp = gpar(fill = 2:3), 
    height = unit(3, "cm")))
v = rnorm(50)
ht_list = ht_list + Heatmap(v, name = "mat2", top_annotation = ha, width = unit(1, "cm"))

split = sample(letters[1:2], 50, replace = TRUE)
lgd_boxplot = Legend(labels = c("group a", "group b"), title = "group",
    legend_gp = gpar(fill = c("red", "blue")))
draw(ht_list, row_split = split, ht_gap = unit(5, "mm"), 
    heatmap_legend_list = list(lgd_boxplot))
```

# Summing Everything up 
```{r}
ha = HeatmapAnnotation( foo = 1:10, 
                        bar = cbind(1:10, 10:1),
                        pt = anno_points(1:10),
                        show_legend = c("bar" = FALSE)
)

Heatmap(matrix(rnorm(100), 10), name = "mat", top_annotation =    ha)
Heatmap(matrix(rnorm(100), 10), name = "mat", bottom_annotation = ha)
```


```{r}
ha2 = rowAnnotation( foo = 1:10, 
                        bar = cbind(1:10, 10:1),
                        pt = anno_points(1:10),
                        show_legend = c("bar" = FALSE)
)

Heatmap(matrix(rnorm(100), 10), name = "mat", right_annotation = ha2)
Heatmap(matrix(rnorm(100), 10), name = "mat", left_annotation = ha2)

```


















